<?php

namespace AppBundle\Repository;

/**
 * ProuctRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProuctRepository extends \Doctrine\ORM\EntityRepository
{
}
