todo:
    resource: "@TodoBundle/Controller/"
    type:     annotation
    prefix:   /

ui_one:
    resource: "@UIOneBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
